removed nested repo

diff --git a/jenkinsfile2 b/jenkinsfile2
--- a/jenkinsfile2
+++ b/jenkinsfile2
@@ -1,83 +1,68 @@
 pipeline {
-
     agent any
 
-
-    parameters {
-
-        string(name: 'ENVIRONMENT', defaultValue: 'dev', description: 'Environment to deploy to')
-
-        booleanParam(name: 'RUN_TESTS', defaultValue: true, description: 'Run tests?')
-
-        choice(name: 'DEPLOY_SERVER', choices: ['dev', 'test', 'prod'], description: 'Choose deployment server')
-
+    tools {
+        maven 'mymaven'
     }
 
+    environment {
+        IMAGE_NAME = 'addressbook-app'
+        CONTAINER_NAME = 'addressbook-container'
+    }
 
     stages {
 
-        stage('Dev Stage') {
-
+        stage('Build') {
             steps {
-
-                script {
-
-                    if (params.ENVIRONMENT == 'dev') {
-
-                        echo "Building for development environment"
-
-                    }
-
-                }
-
+                sh 'mvn clean compile'
             }
-
         }
 
-        stage('Test Stage') {
-
+        stage('Test') {
             steps {
-
-                script {
-
-                    if (params.RUN_TESTS) {
-
-                        echo "Running tests in the ${params.ENVIRONMENT} environment"
-
-                    } else {
-
-                        echo "Skipping tests"
-
-                    }
-
-                }
-
+                sh 'mvn test'
             }
-
         }
 
-        stage('Prod Stage') {
-
+        stage('Package') {
             steps {
-
-                script {
-
-                    if (params.DEPLOY_SERVER == 'prod') {
-
-                        echo "Deploying to production server"
-
-                    } else {
-
-                        echo "Deploying to ${params.DEPLOY_SERVER} server"
-
-                    }
-
-                }
-
+                sh 'mvn package'
             }
-
         }
 
+        stage('Build Docker Image') {
+            steps {
+                sh 'docker build -t $IMAGE_NAME .'
+            }
+        }
+
+        stage('Run Container') {
+            steps {
+                sh '''
+                docker rm -f $CONTAINER_NAME || true
+                docker run -d -p 8081:8080 --name $CONTAINER_NAME $IMAGE_NAME
+                '''
+            }
+        }
+        stage('Push to DockerHub') {
+    steps {
+        withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
+            sh '''
+            echo $PASS | docker login -u $USER --password-stdin
+            docker tag addressbook-app $USER/addressbook-app:latest
+            docker push $USER/addressbook-app:latest
+            '''
+        }
+    }
+}
     }
 
+    post {
+        success {
+            echo '✅ Deployment Successful!'
+        }
+        failure {
+            echo '❌ Pipeline Failed!'
+        }
+    }
 }
